---
path:
  root_dir: /,tmp,dify
  image_dir: assets,image_files
  word_dir: assets,word_files
  convert_dir: assets,image_files,converted
  upload_dir: upload
sync:
  mapping:
    - source:
      target:
upload:
  dataset:
  file_name: product_list.xlsx
  mark_column: 设备名称