---
path:
  root_dir: /,tmp,dify
  image_dir: assets,image_files
  word_dir: assets,word_files
  convert_dir: assets,image_files,converted
  upload_dir: upload
sync:
  mapping:
    - source:
      target:
upload:
  dataset:
  file_name: product_list.xlsx
  mark_column: 设备名称
  keywords_column:
export:
  file_name: qa_info.xlsx
  department: Factory Quality Knowledge
erp:
  dataset: ERP Knowledge Base
  file_name: ERP FAQ Update - 20241024.docx