---
paths:
  root_dir: /,tmp,dify
  sub_dirs:
    image_dir: assets,image_files
    word_dir: assets,word_files
    convert_dir: assets,image_files,converted
    upload_dir: upload
    download_dir: download
sync:
  default:
    skip_existing: false
    replace_existing: true
    remove_extra: false
    preserve_document_order: true
    preserve_segment_order: true
    dataset_mapping:
  dataset:
    skip_existing: false
    replace_existing: true
    remove_extra: false
    preserve_document_order: true
    preserve_segment_order: true
    dataset_mapping:
      - source:
        target:
  agent:
    skip_existing: false
    replace_existing: true
    remove_extra: false
    preserve_document_order: true
    preserve_segment_order: true
  file:
    skip_existing: false
    replace_existing: true
    remove_extra: false
    preserve_document_order: false
    preserve_segment_order: false
  mail:
    skip_existing: false
    replace_existing: true
    remove_extra: false
    preserve_document_order: false
    preserve_segment_order: false
upload:
  docx:
    dataset:
      details: docx files details
      summary: docx files summary
  excel:
    dataset:
    file_name: product_list.xlsx
    mark_column: 设备名称
    keywords_column:
export:
  file_name: qa_info.xlsx
  department: Factory Quality Knowledge
erp:
  dir: erp
  dataset: ERP Knowledge Base
mailboxes:
  - email:
    inbox:
      root_folder: Inbox
      subfolders:
        - name: China Daily News
          category: china daily news
          dataset:
            summary: China Daily News Summary
            details: China Daily News Details
browser:
  headless_mode: true
  timeout: 25
  type:
    - edge