---
paths:
  root_dir: /,tmp,dify
  sub_dirs:
    image_dir: assets,image_files
    word_dir: assets,word_files
    convert_dir: assets,image_files,converted
    upload_dir: upload
sync:
  mapping:
    - source:
      target:
upload:
  docx:
    dataset:
      details: docx files details
      summary: docx files summary
  excel:
    dataset:
    file_name: product_list.xlsx
    mark_column: 设备名称
    keywords_column:
export:
  file_name: qa_info.xlsx
  department: Factory Quality Knowledge
erp:
  dir: erp
  dataset: ERP Knowledge Base
mailboxes:
  - email:
    inbox:
      root_folder: Inbox
      subfolders:
        - name: China Daily News
          category: china daily news
          dataset: China Daily News Knowledge Base